
stips_map = {'payoff-letter': ['10 Day Payoff Letter', '10 Day Payoff Letter - Buyer'],
             'proof-of-income': ['Additional Proof of Income 2', 'Additional Proof of Income 3', 'Proof of Income', 'Proof of Income', 'Proof of Income - Buyer', 'Proof of Income - Buyer - #1', 'Proof of Income - Buyer - #2', 'Proof of Income 1', 'Proof of Income - Buyer - #3'],
             'trade-payoff-quote': ['Additional Trade Payoff Quote', 'Trade Payoff Quote', 'Trade Payoff Quote - Seller'],
             'affidavit': ['Affidavit', 'Affidavit of Heirship'],
             'alternate-id': ['Alternate ID', 'Alternate Id', 'Alternate ID - Buyer'],
             'articles-of-incorporation-organization': ['Articles of Corporation/Organization', 'Articles of Incorporation / Organization'],
             'authorization-letter': ['Authorization Letter', 'Business Authorization Letter'],
             'title-back': ['Back of Additional Trade Title', 'Back of Title', 'Back of Trade Title', 'Title Rear - Seller', 'Title Rear - Seller - #2'],
             'owner-id-back': ['Back of Co-buyer ID', 'Back of Co-seller ID', 'Back of ID', 'Back of Primary Owner ID', 'Back of Second Owner ID'],
             'social-security-card-back': ['Back of Co-Buyer Social Security Card', 'Back of Social Security Card', 'Social Security Card Back - Buyer', 'Social Security Card Back - Cobuyer'],
             'drivers-license-back': ["Back of Driver's License", 'Back of Drivers License', 'Drivers License Back - Buyer', 'Drivers License Back - Cobuyer', 'Drivers License Back - Coseller'],
             'bill-of-lading': ['Bill of Lading', 'Bill of Lading - Buyer'],
             'bill-of-sale': ['Bill of Sale', 'Copy of Bill of Sale', 'Original Signed Bill of Sale', 'Source Bill of Sale'],
             'business-card': ['Business Card'],
             'power-of-attorney': ['Buyer POA', 'Co-buyer POA', 'Original POA Co-Buyer', 'Original Signed Power of Attorney', 'Original Signed Power of Attorney (co-buyer)', 'signed-poa', 'Power of Attorney - State - Buyer'],
             'supplemental-form': ['Buyer Supplemental Form', 'Co-Buyer Supplemental Form', 'Colorado Supplemental Form - Buyer'],
             'buyers-tag': ["Buyer's Tag"],
             'change-of-address': ['Change of Address Form'],
             'proof-of-residence': ['Co-Buyer Proof of Residence', 'Proof of Residence', 'Proof of Residence - Buyer', 'Proof of Residence - Cobuyer', 'Proof of Residency - Buyer', 'proof-of-residency'],
             'loan-agreement': ['Contract /Loan Agreement', 'Installment Contract/Loan Agreement', 'Loan Agreement - Buyer'],
             'emissions-inspection': ['Copy of Emissions Inspection', 'Copy of Emissions Inspection', 'Copy of Smog Inspection', 'Emissions / Smog Inspection', 'Emissions Inspection - Buyer', 'Original Emissions Inspection', 'Original Inspection', 'Original Smog Inspection', 'original-inspection', 'smog-inspection'],
             'lien-release': ['Copy of Lien Release', 'Lien Release', 'Lien Release - Buyer'],
             'lien-release-letter': ['Copy of Lien Release Letter', 'Copy of Lien Release Letter', 'Lien Release Letter', 'Release Letter'],
             'safety-inspection': ['Copy of Safety Inspection', 'Copy of Safety Inspection', 'copy-of-safety-inspection', 'Original Safety Inspection', 'Safety Inspection', 'Safety Inspection Copy'],
             'vin-inspection': ['Copy of VIN Inspection', 'Original VIN Inspection', 'vehicle-inspection-report-copy', 'VIN Inspection - Buyer', 'Vehicle Inspection Report'],
             'insurance': ['current-insurance', 'Insurance Card - Buyer', 'Insurance Card', 'Insurance Declaration Page', 'Insurance Declaration Page - Buyer', 'Proof of Insurance', 'Proof of Insurance - Current Vehicle', 'Proof of Insurance - New Vehicle', 'proof-of-insurance'],
             'damage-disclosure': ['Damage Disclosure Statement'],
             'dealer-funding-request': ['Dealer Funding Request Form', 'Dealer Funding Request Form - Buyer'],
             'dealer-payoff': ['Dealer Payoff'],
             'dealer-reassignment': ['Dealer Reassignment', 'Dealer Reassignment - Buyer'],
             'death-certificate': ['Death Certificate'],
             'divorce-decree': ['Divorce Decree', 'divorce-decree'],
             'draft-letter': ['Draft Letter'],
             'drivers-license-front': ['Drivers License Front', 'Drivers License Front - Buyer', "Front of Co-buyer Driver's License", "Front of Driver's License", 'Front of Drivers License'],
             'temp-tag': ['Extended Temp Tag'],
             'title-front': ['Front of Additional Trade Title', 'Front of Title', 'Front of Trade Title', 'Title Front - Seller', 'Title Front - Seller - #2'],
             'owner-id-front': ['Front of Co-buyer ID', 'Front of Co-seller ID', 'Front of ID', 'Front of Primary Owner ID', 'Front of Second Owner ID', 'Front of Secondary Owner ID', 'Back of Second Owner ID', 'Back of Secondary Owner ID'],
             'social-security-card-front': ['Front of Co-Buyer Social Security Card', 'Front of Social Security Card', 'Social Security Card Front - Buyer', 'Social Security Card Front - Cobuyer'],
             'id-od': ['ID/OD Inspection', 'ID/OD Inspection - Buyer', 'Original Identification Number & Odomete'],
             'testamentary': ['Letter of Testamentary'],
             'license-plate': ['License Plate - Buyer', 'Transfer License Plate'],
             'marriage-license': ['Marriage License', 'marriage-license'],
             'missing-signature': ['Missing Signature', 'missing-signature'],
             'nc-mvr-614': ['NC MVR-614: Principally Garaged Vehicle'],
             'negative-equity-check': ['Negative Equity Check'],
             'reference-document': ['Reference Document', 'Reference Document - Buyer'],
             'odometer': ['Odometer Photo', 'Odometer Photo - Seller', 'Odometer Photo - Buyer', 'Original Signed Odometer Statement', 'Photo of Additional Trade-in Odometer', 'Photo of Mileage', 'Photo of Trade Odometer', 'Photo of Trade-in Odometer', 'Proof of Trade Odometer'],
             'one-in-the-same': ['One in the Same'],
             'weight-slip': ['Original Weight Slip (Trucks)', 'Weight Slip (Trucks)'],
             'other': ['Other'],
             'paid-off-loan-balance': ['Paid Off Auto Loan Balance', 'Paid Off Auto Loan Balance - Buyer', 'Original Paid-Off Auto Loan Balance'],
             'property-tax': ['Paid Property Tax Receipt', 'Paid Property Tax Receipt (prior year)', 'property-tax'],
             'proof-of-business': ['Proof of Business', 'Proof of Business - Buyer'],
             'trade-payoff-proof': ['Proof of Payoff or Trade', 'Proof of Payoff or Trade - Buyer'],
             'proof-of-phone': ['Proof of Phone', 'Proof of Phone - Buyer'], 'social-security-card': ['Proof Of Social Security Card'], 'references': ['References'], 'safeguard-contract-terms': ['Safeguard Contract Terms'], 'sales-tax-form': ['Sales Tax Form'], 'statement-of-fact': ['Statement of Fact'], 'tin': ['Tax Payer Identification Number'], 'tax-return': ['Tax Return', 'tax-return'], 'title': ['Title', 'vehicle-title'],
             'title-application': ['Title Application', 'Title Application - Buyer'], 'title-memorandum': ['Title Memorandum'], 'total-loss-declaration': ['Total Loss Declaration'], 'tribal-claim': ['Tribal Claim'], 'UACC_334': ['UACC_334'], 'UACC_338': ['UACC_338'], 'UACC_340': ['UACC_340'], 'UACC_342': ['UACC_342'], 'UACC_362': ['UACC_362'], 'UACC_375': ['UACC_375'], 'use-tax-cert': ['Use Tax Certificate', 'use-tax-cert'], 'vehicle-assessment': ['Vehicle Assessment'], 'vehicle-registration': ['Vehicle Registration', 'Vehicle Registration - Buyer']}

